// import ProtectedRoute from "@/components/ProtectedRoute";
// import Sidebar from "@/components/Dashboard/Functions/Sidebar";

// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>{children}</body>
//     </html>
//   )
// }


import Sidebar from "@/components/Dashboard/Functions/Sidebar";
import ProtectedRoute from "@/components/ProtectedRoute";

export default function ProfileLayout({ children }) {
  return (
    <ProtectedRoute>
      <div className="profile-layout">
        <div className="profile-sidebar"><Sidebar/></div>
        <div className="profile-main">
          {children}
        </div>
      </div>
    </ProtectedRoute>
  );
}